#
# setParamメイン窓のトップメニュー
#
set t(option,setLanguage) "言語設定"

set t(file)                      "ファイル"
set t(file,choosesaveDir)        "保存フォルダの変更"
set t(file,readParamFile)        "原音パラメータの読み込み  (Ctrl+o)"
set t(file,saveParamFile)        "上書き保存                     (Ctrl+s)"
set t(file,saveParamFileAs)      "名前を付けて保存             (Ctrl+Shift+s)"
set t(file,mergeParamFile)       "別の原音パラメータをマージ"
set t(file,readSettings)         "初期化ファイルを指定して読み込む"
set t(file,saveSettings)         "現在の設定を初期化ファイルに保存"
set t(file,readUstFile)          "ustファイルを読んで編集対象を最小限に絞る"
set t(file,dirHistory)           "最近使ったフォルダを開く"
set t(file,pDirHistory)          "最近使った親フォルダを開く"

set t(file,test)                 "通常使わない機能"
set t(file,test,makeRecList)     "保存フォルダのwavファイルから発声リストを作成"
set t(file,test,makeRecList,msg) "音名リスト、発声タイプリストを更新しました"
set t(file,test,readRecList)     "音名リストの読み込み"
set t(file,test,saveRecList)     "音名リストの保存"
set t(file,test,readTypeList)    "発声タイプリストの読み込み"
set t(file,Exit)                 "終了"

set t(edit)                      "編集"
set t(edit,tk_tableCopy)         "コピー   (Ctrl+c)"
set t(edit,pasteCell)            "貼り付け (Ctrl+v)"
set t(edit,searchParam)          "検索     (Ctrl+f)"
set t(edit,doSearchParam1)       "次を検索 (Ctrl+g, Ctrl+n)"
set t(edit,doSearchParam0)       "前を検索 (Ctrl+G, Ctrl+N)"
set t(edit,changeCell)           "選択中の範囲の値を一括変更 (Ctrl+m)"
set t(edit,estimateParam)        "パラメータ自動推定(単独音用)"
set t(edit,zeroCross)            "各パラメータのゼロクロス補正"
set t(edit,copyWithSpace)        "空白区切りで…"
set t(edit,copyCellWithSpace)    "コピー"
set t(edit,pasteCellWithSpace)   "貼り付け"
set t(edit,duplicateEntp)        "行を複製する  (Ctrl+i)"
set t(edit,deleteEntp)           "行を削除する  (Ctrl+d)"

set t(show)                      "表示"
set t(show,showSpec)             "スペクトルを表示"
set t(show,showpow)              "パワーを表示"
set t(show,showf0)               "F0を表示"
set t(show,pitchGuide)           "音叉窓を表示"
set t(show,zoomTitle)            "横軸の拡大"
set t(show,timeAxis)             "時間軸"
set t(show,timeAxisSec)          "秒単位"
set t(show,timeAxisBar)          "小節単位"

set t(option)                    "オプション"
set t(option,gui)                "マウス、キー操作の設定"
set t(option,S)                  "マウスで左ブランクを動かしたとき、"
set t(option,S,1)                "他パラメータも一緒に動かして相対的な位置関係を保つ。(Shift+l)"
set t(option,S,2)                "他パラメータは動かさず、左ブランクのみを動かす。(CShift+l)"
set t(option,E)                  "右ブランク値の表現方法"
set t(option,E,1)                "ファイル末尾からの時間(正の値で表現。UTAU v0.2.43以前用)"
set t(option,E,2)                "左ブランクからの時間(負の値で表現。UTAU v0.2.45beta版以降用)"
set t(option,P)                  "マウスで先行発声を動かしたとき、"
set t(option,P,1)                "他パラメータも一緒に動かして相対的な位置関係を保つ。(Shift+p)"
set t(option,P,2)                "他パラメータは動かさず、先行発声のみを動かす。(Shift+p)"
set t(option,minusO)             "オーバーラップを負にしても良い"
set t(option,blankBroom)         "左右ブランクの移動可能範囲を他パラメータより優先する"
set t(option,cutBlank)           "F9で左右ブランクの両側波形をカットする(単独音向け機能)"
set t(option,timingAdjMode)      "発声タイミング補正モード"
#set t(option,unusual)            "本来使わない機能"
#set t(option,removeDC)           "録音後にDC成分を除去する"
#set t(option,rec)                "録音機能を使う"
set t(option,uttTimingSettings)  "発声タイミングチェックの設定(再生=F8)"
set t(option,ioSettings)         "オーディオI/O設定"
set t(option,settings)           "詳細設定"
set t(option,setPlayRange)       "指定範囲再生の設定"
set t(option,synTestWindow)      "合成テストの設定(再生=F10)"
set t(option,clickPlayRangeMode) "画面クリックで近傍パラメータ間を再生する"
set t(option,autoFocus)          "パラメータへの自動フォーカス設定"

set t(tool)                      "ツール"
set t(tool,auto)                 "原音パラメータの自動推定"
set t(tool,auto,estimateParam)       "単独音の自動推定"
set t(tool,auto,autoParamEstimation) "単独音の自動推定その2(外部ツール：りぶあん)"
set t(tool,auto,genParam)            "連続音の自動推定"
set t(tool,auto,plugin)              "プラグイン"
set t(tool,removeDCall)          "DC成分の一括除去"
set t(tool,addUnderScore)        "wavファイル名の先頭に「_」を追加(連続音用)"
set t(tool,addUnderScore2)       "wavファイル名(や周波数ファイル)の先頭に「_」を追加(連続音用)"
set t(tool,test)                 "テスト中"
set t(tool,cutWav)               "wavの両端を一括カット"
set t(tool,changeAlias)          "エイリアス一括変更"
set t(tool,convertMonoAll)       "wavファイルの一括モノラル化"
set t(tool,wav)                  "wavファイルの一括編集"
set t(tool,zeroCross)            "各パラメータのゼロクロス補正"
set t(tool,runExplorer)          "保存フォルダをエクスプローラで開く"

set t(tool,finish)                 "仕上げ、補完用ツール"
set t(tool,finish,aliasComplement) "連続音oto.iniに無いエイリアスを探し、単独音で補完する"
set t(tool,finish,woComplement)    "「を」が無い場合「お」で補完する"
set t(tool,sort)                   "パラメータ一覧の並び替え"
set t(tool,sort,sortByVowel)       "仮名順に並び替え"
set t(tool,sort,sortByFID)         "wavファイル名順に並び替え"

set t(help)                      "ヘルプ"
set t(help,onlineHelp)           "オンラインマニュアル"
set t(help,Version)              "バージョン"
set t(help,official1)            "公式ページを開く"
set t(help,official2)            "公式ページ(配布場所)を開く"

#
# setParamメイン窓のその他のラベル
#
set t(.saveDir.midashi)     "保存フォルダ："

